### PR TITLE
added domain name resolving before connection for wg/awg and xray protocols

### LINKED ISSUE #801: Feature Request: Connect Using Domain
In scenarios where a physical server, such as a NAS, is situated in a location with a dynamic IP address provided by the Internet Service Provider. However it is possible to configure a domain name using Dynamic DNS. It would greatly enhance the utility of such home servers to have the capability to serve as VPN hosts.

As my expertise in VPN protocols is limited, I seek clarification on the possibility of configuring an Amnezia server solely with a public domain name. If it's is possible, so maybe implement this feature

### LINKED ISSUE #823: Error: 1000
Version 4.5.3.0 (maybe earlier, I have not used it for a long time) for Android refuses to work (error 1000), when a domain name is indicated in the config, if it is changed to IP, then everything works.

It does not depend on the DNS settings, i.e. The program is not even trying to resolve the address.

**Smartphone:**
 - OS: Android 11
 - Version Amnezia: 4.5.3.0

### LINKED ISSUE #892: Allow to enter domain instead of the ip address of the server
In case that the IP gets blocked in the country we can change the IP behind the domain instead of sharing new connections to the users.

### PR DESCRIPTION
**Pull request by Nethius**

### CODE REVIEW

**Comment by sbh96** [comment]
please push this feature/awg-wg-name-resolving fast as possible to master branch we need it in iran thanks

**Comment by mikkyornyx** [comment]
> please push this feature/awg-wg-name-resolving fast as possible to master branch we need it in iran thanks

+1, it is quite inconvenient to use it with IP instead of domain name (especially while having dynamic dns). BTW, iOS client resolves domain well, so this issue appears to be only with Android.

**Comment by Nethius** [comment]
If someone can test this branch, it will help us a lot. Domain name resolve should work for awg/wg protocols

**Comment by snoups** [comment]
развернул 3xui, установил домен и серты. 
На Windows - только ip
На MacOS - только по ip
На IOS - по ip и домену

xray, amnezia 4.6.0.3

Поправьте пж

**Comment by mikkyornyx** [comment]
> развернул 3xui, установил домен и серты. На Windows - только ip На MacOS - только по ip На IOS - по ip и домену
> 
> xray, amnezia 4.6.0.3
> 
> Поправьте пж

Translating: Installed 3xui, deployed domain and certificates. Windows and MacOS clients only connect using IP. iOS works with both domain and IP.
Please fix.

Вообще, по-моему это изменение только для клиента Android было.

**Comment by virtualos** [comment]
Device -> Mobile Android 14
Domain -> xxx.com
Used Cloudflare for A record to connect xxx.com to server IP (Not proxified).
Is Amnezia succeed to install Xray and AmneziaWG? -> YES
Did VPN connect? -> NO, Error Code 1000

**Comment by virtualos** [comment]
> If someone can test this branch, it will help us a lot. Domain name resolve should work for awg/wg protocols

I tested dev build:
added the ability to enter a domain name when configuring the server #3161
https://github.com/amnezia-vpn/amnezia-client/actions/runs/10318395547/artifacts/1794715477

Server: Hetzner Data center
OS: Ubuntu 22.04
Amnezia: Android
Domain: 94web.com and in Cloudflare domain linked to server IP by A record with No proxy!

Summery:
I successfully installed AmneziaWG but when I tried to connect I got 1000 error code.

Here is Amnezia Log report:

`Model: A063
Brand: Nothing
Product: Spacewar
Device: Spacewar
Codename: REL
Release: 14
SDK: 34
ABI: arm64-v8a, armeabi-v7a, armeabi

08-18 05:25:46.973 21590 21614 D [qtMainLoopThread] AmneziaQt: Call activity method: exportLogsFile

LOGCAT:
--------- beginning of main
08-18 05:23:20.340 20484 20484 E org.amnezia.vpn: Not starting debugger since process cannot load the jdwp agent.
08-18 05:23:20.673 20484 20507 E OpenGLRenderer: Unable to match the desired swap behavior.
08-18 05:23:33.508 20484 20507 E OpenGLRenderer: Unable to match the desired swap behavior.
08-18 05:23:40.281 20484 20507 E OpenGLRenderer: Unable to match the desired swap behavior.
08-18 05:25:12.142 21163 21163 E org.amnezia.vpn: Not starting debugger since process cannot load the jdwp agent.
08-18 05:25:12.370 21163 21185 E OpenGLRenderer: Unable to match the desired swap behavior.
08-18 05:25:16.150 21163 21185 E OpenGLRenderer: Unable to match the desired swap behavior.
08-18 05:25:18.299 21304 21304 E neziaAwgService: Not starting debugger since process cannot load the jdwp agent.
08-18 05:25:19.145 21304 21325 E AmneziaVpnService: Not a numeric address: 94web.com
08-18 05:25:19.151 21163 21163 E AmneziaActivity: From VpnService: Not a numeric address: 94web.com
08-18 05:25:35.742 21590 21590 E org.amnezia.vpn: Not starting debugger since process cannot load the jdwp agent.
08-18 05:25:35.974 21590 21611 E OpenGLRenderer: Unable to match the desired swap behavior.`

**Review by pokamest — APPROVED** [review]

**Comment by ypurpl** [comment]
I also get error code 1000, following same steps using that build

**Comment by Nethius** [comment]
> I also get error code 1000, following same steps using that build

@vvirtues   check with the latest dev build

**Comment by ypurpl** [comment]
> > I also get error code 1000, following same steps using that build
> 
> @vvirtues check with the latest dev build

I still get it. Should I delete the server and reinstall client and setup all over again?

**Comment by Nethius** [comment]
> > > I also get error code 1000, following same steps using that build
> > 
> > 
> > @vvirtues check with the latest dev build
> 
> I still get it. Should I delete the server and reinstall client and setup all over again?

yep, try to reinstall

**Comment by ypurpl** [comment]
still get it
I also noticed that even though it uses docker, I don't see any containers on Docker Desktop. btw, im using it on Windows and sshing to WSL2

**Comment by vvirtues** [comment]
I realized my configuration looks like this. It is not starting the docker container
```conf
[Interface]
Address = 10.8.1.2/32
DNS = 1.1.1.1, 1.0.0.1
PrivateKey = REDACTED
Jc = 3
Jmin = 10
Jmax = 50
S1 = 23
S2 = 148
H1 = 820074701
H2 = 1986994351
H3 = 1290441021
H4 = 1880645917

[Peer]
PublicKey = 
PresharedKey = 
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = cribsafehouseattire.ddns.net:35433
PersistentKeepalive = 25
```
My peer keys are empty for some reason

**Comment by ypurpl** [comment]
I realized my configuration looks like this. It is not starting the docker container
```conf
[Interface]
Address = 10.8.1.2/32
DNS = 1.1.1.1, 1.0.0.1
PrivateKey = REDACTED
Jc = 3
Jmin = 10
Jmax = 50
S1 = 23
S2 = 148
H1 = 820074701
H2 = 1986994351
H3 = 1290441021
H4 = 1880645917

[Peer]
PublicKey = 
PresharedKey = 
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = REDACTED:35433
PersistentKeepalive = 25
```
My peer keys are empty for some reason

**Comment by ypurpl** [comment]
Is it because I'm not using root?

**Pull request merged**
