### PR TITLE
added conversion using the system locale

### PR DESCRIPTION
**Pull request by Nethius**

### CODE REVIEW

**Comment by useribs** [comment]
Googling revealed there is utf8 method. isn't it a more versatile option? https://doc.qt.io/qt-6/qstring.html#toUtf8

**Comment by Nethius** [comment]
> Googling revealed there is utf8 method. isn't it a more versatile option? https://doc.qt.io/qt-6/qstring.html#toUtf8

I tried toUtf8(), but when using this method, the application keeps crashing

**Review by Noxius87 — CHANGES_REQUESTED** [review]
There's a problem. On MacOS Catalina 10.15 containers are not connected after installation

**Review by Noxius87 — CHANGES_REQUESTED** [review]
AWG protocol does not connect after installation, when trying to install another protocol the application crashes on Windows 11

**Pull request merged**
