### PR TITLE
feature/xray user management

### LINKED ISSUE #902: Bug: Can't see and manage users of the XRay protocol
**Describe the bug**
In the share VPN menu, the "Users" list is empty. It does not show any clients, including the admin sessions, while it works fine for other protocols, such as OpenVPN over Cloak and AmneziaWG

**Screenshots**
XRay (the users list is empty!):
image

OpenVPN over Cloak:
image

**Desktop:**
 - OS: Windows 10
 - Version: 4.6.0.3

**Server:**
 - OS: Debian 12

### LINKED ISSUE #960: Feature: add client management for Xray
### for append client
1. add id generation when creating a connection config
2. add the user id to the server config
3. restart xray on the server
4. append client info to clients table

### for revoke client
1. remove the user id from the server config
2. restart xray on the server
3. remove client info from clients table

I think the workflow will be similar to adding/removing configs for wg/awg
wg config creation - https://github.com/amnezia-vpn/amnezia-client/blob/dev/client/configurators/wireguard_configurator.cpp
xray config creation - https://github.com/amnezia-vpn/amnezia-client/blob/dev/client/configurators/xray_configurator.cpp
user management - https://github.com/amnezia-vpn/amnezia-client/blob/dev/client/ui/models/clientManagementModel.cpp

### LINKED ISSUE #1236: Users list don't showing on MacOS with XRAY protocol
**Describe the bug**
When I generate new users for AmneziaWG protocol – I can view list of users and revoke profiles. But for Xray protocol last version (pre-release 2 weeks ago) of Mac OS application for ARM chips – don’t show me user list. 

**To Reproduce**
1. Deploy server with Xray protocol
2. Add new user and generate profile
3. Go to screen with users list for each server
4. See empty user list

**Expected behavior**
A full user list like AmneziaWG protocol.

**Screenshots**

Screenshot 2024-11-06 at 19 23 06

**Desktop (please complete the following information):**
 - OS: MacOS 15.0 (same error for previous OS\)
 - Version (i can't copy):
Screenshot 2024-11-06 at 19 51 07

**Server (please complete the following information):**
 - OS: Ubuntu 24.04 and 22.04

### PR DESCRIPTION
**Pull request by CyAn84**
# This PR adds XRay client id and user id and saves them in clients table

- for append client:
1. add id generation when creating a connection config
2. add the user id to the server config
3. restart xray on the server
4. append client info to clients table

- for revoke client
1. remove the user id from the server config
2. restart xray on the server
3. remove client info from clients table

### CODE REVIEW

**Comment by CyAn84** [comment]
@Nethius "restart xray on the server" means restart xray service inside docker container or restart xray docker container itself?

**Comment by IvanKhramov** [comment]
Hello.
What is the expected time frame for this fix to be accepted?
There is a huge lack of user experience for the xRay protocol.

**Comment by 0eale0** [comment]
@pokamest

**Comment by utmaks** [comment]
I can help with early builds (mac os arm chips) to test this feature.

**UPD**

Tested latest build from artifacts:
- Users list showing me only one "Client 0" without real name used when I created it
- Connect to any VPN: AmneziaWG / Xray was unsuccessful (latest pre-release working normally)

PR requires re-installation VPN on the server?

**Comment by aiamnezia** [comment]
@utmaks "Client 0" appears to be the default client that was previously on the server. You can go ahead and delete it in this version. However, this indicates that a new client has not been added yet. The PR is not ready.  We are still working on some issues. I will fix them soon.

**Comment by utmaks** [comment]
New manual tests for latest build, test cases:
- I can view users after create a new one:
   + can view users for original xray format
   + can view users for amnezia xray format
- I can revoke access both for original and xray format. It's revoke immediately but internet connection on client side goes to full down until pressing "Connect" button again

Thanks!

**Comment by aiamnezia** [comment]
> New manual tests for latest build, test cases:
> 
> * I can view users after create a new one:
>   
>   * can view users for original xray format
>   * can view users for amnezia xray format
> * I can revoke access both for original and xray format. It's revoke immediately but internet connection on client side goes to full down until pressing "Connect" button again
> 
> Thanks!

Thank you for your feedback!
When you install Xray on the server and connect for the first time, a new user should appear in the client table for the client used during installation. Do you see this user? Did you revoke it?

**Comment by utmaks** [comment]
> Do you see this user? Did you revoke it?

Installation on the server was done with stable client before experiments with this PR. So after I installed latest artifact I saw in the user list `Client 0` username. I didn't try to revoke it. There were no other users on the list.

All experiments with user revoking was done with new clients created right there.

**Review by Nethius — APPROVED** [review]

**Pull request merged**
